### PR TITLE
Feature/excel parse tests

### PR DESCRIPTION
**Pull request by andrewphilipsmith**

### CODE REVIEW

**Comment by andrewphilipsmith** [comment]
Not yet for mmerging

**Comment by andrewphilipsmith** [comment]
Travis is now failing for the right reasons - actual failing tests rather than any config problems. Still need to either fix or disable Appveyor, so that the CI feedback in Github is meaningful.

**Comment by andrewphilipsmith** [comment]
I believe this is now ready to merge with master. @stringfellow

**Comment by stringfellow** [comment]
Looks good! :+1:

**Pull request merged**
